/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bomberman;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JToolBar;

/**
 *
 * @author Juan Carlos Aragón
 */
public class Game extends javax.swing.JFrame {
	public static Celda[][] celda;
	public static int filas = 12, columnas = 12;
	private JPanel  pnlCelda, pnl;
	private JScrollPane scrollPane;
	private JButton btnRpMenu, btnRpFunUsada, btnRpGraficas;
	private JToolBar barraReportes;
	private GridLayout layout, layoutEnd;
    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        CrearComponentes();
        CrearMatriz();
    }
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }
	private void CrearComponentes(){
		 layout = new GridLayout(0,4);
        pnl = new JPanel();
        pnl.setLayout(layout);
		 barraReportes = new JToolBar();
		 btnRpGraficas = new JButton(" | RP. GRAFICAS | ");
        btnRpGraficas.setName(" | RP. GRAFICAS | ");
        barraReportes.add(btnRpGraficas);
        pnl.add(barraReportes);
		
		pnlCelda = new JPanel(null);
		scrollPane = new JScrollPane(pnlCelda, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
		this.add(scrollPane, BorderLayout.CENTER);
		this.add(pnl, BorderLayout.PAGE_START);
		this.setSize(700, 700);
		this.setLocationRelativeTo(null);
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	}
	
	//Crear ambiente
	private void CrearMatriz(){
		celda = new Celda[filas][columnas]; //Se crea la matriz de labels
		pnlCelda.setLayout(new GridLayout (filas,columnas)); //Le insertamos el estilo celda
		pnlCelda.removeAll(); //Limpiamos el panel.		
		celda = new Celda[filas][columnas]; //Se crea la matriz de labels
		
		for(int fila = 0 ; fila < filas; fila++){ //Iniciamos con fila, luego con la columna
			for(int columna = 0 ; columna < columnas; columna++){
				//celda[fila][columna] = new Celda((78 * columna),(35 * fila), 30, 15);
				pnlCelda.setPreferredSize(new Dimension(30, 15));
				pnlCelda.add(celda[fila][columna]);

			}
		}
		pnlCelda.updateUI(); //Se actualiza el panel, para ver lo que agregamos.
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
