/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bomberman;

import POJOMN.Usuario;

/**
 *
 * @author Juan Carlos Aragón
 */
public class UserRequest extends javax.swing.JFrame {

    /**
     * Creates new form UserRequest
     */
    public UserRequest() {
        initComponents();
	this.setDefaultCloseOperation(DISPOSE_ON_CLOSE); 
	actualizar();
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxUsuarios = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnDeclinar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbxUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Usuarios");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnDeclinar.setText("Declinar");
        btnDeclinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclinarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(cbxUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addGap(86, 86, 86)
                        .addComponent(btnDeclinar)))
                .addGap(203, 203, 203))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnDeclinar))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here: Borrar de solicitud y Insertar en registro
	Archivo.getInstancia().setTipo(2); //Borrar y Insertar
	
	for(Usuario usu : Archivo.getInstancia().getLstUsuarios()){
		if(usu.getUsuario().equals(cbxUsuarios.getSelectedItem().toString())){
			Usuario.getInstancia().setPass(usu.getPass());
			Usuario.getInstancia().setUsuario(usu.getUsuario());
			Archivo.getInstancia().getLstUsuarios().remove(usu);
			break;
		}
	}
	
	Archivo.getInstancia().quitar("solicitud//usuarios.solicitud");
	Archivo.getInstancia().insertar("registro//usuarios.registro");
	actualizar();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnDeclinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclinarActionPerformed
        // TODO add your handling code here:
	for(Usuario usu : Archivo.getInstancia().getLstUsuarios()){
		if(usu.getUsuario().equals(cbxUsuarios.getSelectedItem().toString())){
			Usuario.getInstancia().setUsuario(usu.getUsuario());
			Usuario.getInstancia().setPass(usu.getPass());
			Archivo.getInstancia().getLstUsuarios().remove(usu);
			break;
		}
	}
	Archivo.getInstancia().quitar("solicitud//usuarios.solicitud");
	actualizar();
    }//GEN-LAST:event_btnDeclinarActionPerformed

	private void actualizar(){
		Archivo.getInstancia().setTipo(1);
		Archivo.getInstancia().buscar("solicitud//usuarios.solicitud");
		cbxUsuarios.removeAllItems();
		int cont = 0;
		for (Usuario usu : Archivo.getInstancia().getLstUsuarios()) {
			cbxUsuarios.addItem(usu.getUsuario());
			if(cont++ == 0){
				cbxUsuarios.setSelectedItem(usu);
			}
		}
		
	}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRequest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnDeclinar;
    private javax.swing.JComboBox<String> cbxUsuarios;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
